version: '3.3'

services:

  db:
    image: postgres:13.10
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: DDExpo/foodgram-backend:latest
    volumes:
      - static_vol:/backend_static
      - media_vol:/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: DDExpo/foodgram-frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_vol:/frontend_static/
    depends_on:
      - backend

  nginx:
    image: DDExpo/foodgram_nginx:latest
    env_file: .env
    depends_on:
      - backend
      - frontend
      - db
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    restart: always

volumes:
  static_vol:
  media_vol:
  postgres_vol:
